#!/usr/bin/env bash
# Generated by review charter v1, 2026-05-15
#
# Vowrite Review Scan — 综合代码审查脚本
# 串行运行 8 个检查步骤，每步标注 PASS / FAIL / SKIPPED，最后汇总。
#
# 设计原则（防坑）:
#   - 即使 swiftlint / swift-format / gitleaks 全部缺失，步骤 5+8 的 grep 扫描必须能跑。
#   - --soft 模式下 P2/P3 命中退出码转为 0（不阻塞 CI soft 起步阶段）。
#   - --ci 模式输出 GitHub Actions annotation 格式。
#
# 用法:
#   ops/scripts/review-scan.sh [OPTIONS]
#
# 选项:
#   --report <path>    将结果写入 Markdown 报告文件
#   --ci               GitHub Actions annotation 格式输出
#   --rule <Lxx>       只运行指定步骤 (L1-L8)
#   --soft             P2/P3 命中退出码降为 0
#
# 退出码:
#   0  全部通过（或 --soft 模式下 P2/P3 命中）
#   1  P0 或 P1 级别命中
#   2  P2 或 P3 级别命中（--soft 时降为 0）

set -uo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# 参数解析
# ─────────────────────────────────────────────────────────────────────────────
REPORT_PATH=""
CI_MODE=false
ONLY_RULE=""
SOFT_MODE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --report)  REPORT_PATH="$2"; shift 2 ;;
        --ci)      CI_MODE=true; shift ;;
        --rule)    ONLY_RULE="$2"; shift 2 ;;
        --soft)    SOFT_MODE=true; shift ;;
        *)         echo "Unknown option: $1"; shift ;;
    esac
done

# ─────────────────────────────────────────────────────────────────────────────
# 路径设置
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
KIT_DIR="${REPO_ROOT}/VowriteKit"
MAC_DIR="${REPO_ROOT}/VowriteMac"

WARN_BASELINE=4  # 已知 release build warning 基准值

# ─────────────────────────────────────────────────────────────────────────────
# 状态跟踪
# ─────────────────────────────────────────────────────────────────────────────
PASS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0
P0_P1_HIT=false
P2_P3_HIT=false

declare -a STEP_RESULTS=()

# ─────────────────────────────────────────────────────────────────────────────
# 工具函数
# ─────────────────────────────────────────────────────────────────────────────
hr() { printf '%s\n' "────────────────────────────────────────────────────────────"; }

step_pass() {
    local step="$1" msg="$2"
    PASS_COUNT=$((PASS_COUNT + 1))
    STEP_RESULTS+=("PASS  | $step | $msg")
    echo "✅ PASS  [$step] $msg"
}

step_fail() {
    local step="$1" msg="$2" priority="${3:-P2}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    STEP_RESULTS+=("FAIL  | $step | [$priority] $msg")
    if $CI_MODE; then
        echo "::error::[$step] $msg"
    fi
    echo "❌ FAIL  [$step] [$priority] $msg"
    if [[ "$priority" == "P0" || "$priority" == "P1" ]]; then
        P0_P1_HIT=true
    else
        P2_P3_HIT=true
    fi
}

step_skip() {
    local step="$1" msg="$2"
    SKIP_COUNT=$((SKIP_COUNT + 1))
    STEP_RESULTS+=("SKIP  | $step | $msg")
    echo "⏭  SKIP  [$step] $msg"
}

step_warn() {
    local step="$1" msg="$2"
    STEP_RESULTS+=("WARN  | $step | $msg")
    if $CI_MODE; then
        echo "::warning::[$step] $msg"
    fi
    echo "⚠️  WARN  [$step] $msg"
}

should_run() {
    local step="$1"
    [[ -z "$ONLY_RULE" || "$ONLY_RULE" == "$step" ]]
}

# ─────────────────────────────────────────────────────────────────────────────
# 报告初始化
# ─────────────────────────────────────────────────────────────────────────────
REPORT_LINES=()
report() { REPORT_LINES+=("$1"); }

START_TIME=$(date '+%Y-%m-%d %H:%M:%S')

echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  Vowrite Review Scan  —  $START_TIME"
echo "══════════════════════════════════════════════════════════════"
report "# Vowrite Review Scan Report"
report ""
report "**Run date:** $START_TIME  "
report "**Mode:** $(${SOFT_MODE} && echo 'soft' || echo 'hard')  "
report ""

# ─────────────────────────────────────────────────────────────────────────────
# L1 — Release Build + Warning Baseline
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L1"; then
    echo ""
    hr
    echo "▶ L1 — Release Build (VowriteMac)"
    report "## L1 — Release Build"
    report ""

    BUILD_LOG="$(mktemp /tmp/vowrite-build-XXXXXX.log)"
    BUILD_OK=false
    BUILD_OUTPUT=""

    if cd "${MAC_DIR}" && BUILD_OUTPUT=$(swift build -c release 2>&1 | tee "$BUILD_LOG"); then
        BUILD_OK=true
    fi

    if $BUILD_OK && grep -q "Build complete" "$BUILD_LOG"; then
        WARN_COUNT=$(grep -c "warning:" "$BUILD_LOG" || true)
        if [ "$WARN_COUNT" -le "$WARN_BASELINE" ]; then
            step_pass "L1" "Release build succeeded. Warnings: $WARN_COUNT (baseline: $WARN_BASELINE)"
            report "- **Result:** PASS"
            report "- **Warnings:** $WARN_COUNT / $WARN_BASELINE"
        else
            DELTA=$((WARN_COUNT - WARN_BASELINE))
            step_fail "L1" "Release build: $WARN_COUNT warnings (+$DELTA above baseline $WARN_BASELINE)" "P2"
            report "- **Result:** FAIL (P2)"
            report "- **Warnings:** $WARN_COUNT / $WARN_BASELINE (+$DELTA)"
        fi
    else
        step_fail "L1" "Release build FAILED" "P0"
        report "- **Result:** FAIL (P0) — build failed"
        # Print last 20 lines of build output for diagnosis
        tail -20 "$BUILD_LOG" 2>/dev/null || true
    fi
    rm -f "$BUILD_LOG"
fi

# ─────────────────────────────────────────────────────────────────────────────
# L2 — VowriteKit Unit Tests
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L2"; then
    echo ""
    hr
    echo "▶ L2 — VowriteKit Unit Tests"
    report ""
    report "## L2 — VowriteKit Unit Tests"

    TEST_LOG="$(mktemp /tmp/vowrite-test-XXXXXX.log)"
    cd "${KIT_DIR}" && swift test 2>&1 | tee "$TEST_LOG" || true
    # Accept either classic XCTest "All tests passed" or swift-testing "0 tests in 0 suites passed"
    if grep -qE "(Test Suite 'All tests' passed|Test run with [0-9]+ tests.*passed)" "$TEST_LOG"; then
        PASS_TESTS=$(grep -c "Test Case.*passed\|tests.*passed" "$TEST_LOG" || true)
        step_pass "L2" "Unit tests passed"
        report "- **Result:** PASS"
    else
        FAIL_TESTS=$(grep -c "Test Case.*failed\|failure" "$TEST_LOG" || true)
        step_fail "L2" "Unit tests failed ($FAIL_TESTS failure(s))" "P1"
        report "- **Result:** FAIL (P1) — $FAIL_TESTS failure(s)"
    fi
    rm -f "$TEST_LOG"
fi

# ─────────────────────────────────────────────────────────────────────────────
# L3 — SwiftLint
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L3"; then
    echo ""
    hr
    echo "▶ L3 — SwiftLint"
    report ""
    report "## L3 — SwiftLint"

    if command -v swiftlint &>/dev/null; then
        LINT_LOG="$(mktemp /tmp/vowrite-lint-XXXXXX.log)"
        cd "${REPO_ROOT}" && swiftlint lint --config .swiftlint.yml 2>&1 | tee "$LINT_LOG" || true

        ERROR_COUNT=$(grep -c " error:" "$LINT_LOG" || true)
        WARN_COUNT=$(grep -c " warning:" "$LINT_LOG" || true)

        if [ "$ERROR_COUNT" -gt 0 ]; then
            step_fail "L3" "SwiftLint: $ERROR_COUNT error(s), $WARN_COUNT warning(s)" "P2"
            report "- **Result:** FAIL (P2) — $ERROR_COUNT errors, $WARN_COUNT warnings"
        else
            step_pass "L3" "SwiftLint: 0 errors, $WARN_COUNT warning(s)"
            report "- **Result:** PASS — 0 errors, $WARN_COUNT warnings"
        fi
        rm -f "$LINT_LOG"
    else
        step_skip "L3" "swiftlint not installed (brew install swiftlint)"
        report "- **Result:** SKIPPED — swiftlint not found"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# L4 — swift-format lint
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L4"; then
    echo ""
    hr
    echo "▶ L4 — swift-format lint (report only)"
    report ""
    report "## L4 — swift-format"

    if command -v swift-format &>/dev/null; then
        FMT_LOG="$(mktemp /tmp/vowrite-fmt-XXXXXX.log)"
        cd "${REPO_ROOT}" && swift-format lint -r \
            VowriteKit/Sources \
            VowriteMac/Sources \
            VowriteIOS/Sources \
            VowriteKeyboard/Sources \
            --configuration .swift-format 2>&1 | tee "$FMT_LOG" || true

        FMT_ISSUE_COUNT=$(wc -l < "$FMT_LOG" | tr -d ' ')
        if [ "$FMT_ISSUE_COUNT" -eq 0 ]; then
            step_pass "L4" "swift-format: no issues"
            report "- **Result:** PASS — no issues"
        else
            # swift-format is advisory — always WARN not FAIL
            step_warn "L4" "swift-format: $FMT_ISSUE_COUNT issue(s) (advisory, not blocking)"
            step_pass "L4" "swift-format lint complete (issues logged, not blocking)"
            report "- **Result:** ADVISORY — $FMT_ISSUE_COUNT issue(s)"
        fi
        rm -f "$FMT_LOG"
    else
        step_skip "L4" "swift-format not installed (brew install swift-format)"
        report "- **Result:** SKIPPED — swift-format not found"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# L5 — Secret Scanning (gitleaks with grep fallback)
# NOTE: This step always runs even if gitleaks is missing (grep fallback ensures coverage)
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L5"; then
    echo ""
    hr
    echo "▶ L5 — Secret Scanning"
    report ""
    report "## L5 — Secret Scanning"

    L5_SECRET_FOUND=false

    if command -v gitleaks &>/dev/null; then
        echo "   Using gitleaks (full history scan)..."
        LEAKS_LOG="$(mktemp /tmp/vowrite-leaks-XXXXXX.log)"
        if cd "${REPO_ROOT}" && gitleaks detect --no-banner --redact --config .gitleaks.toml 2>&1 | tee "$LEAKS_LOG"; then
            step_pass "L5" "gitleaks: no secrets detected in history"
            report "- **Result:** PASS — gitleaks clean"
        else
            step_fail "L5" "gitleaks: potential secrets detected — see output above" "P0"
            report "- **Result:** FAIL (P0) — gitleaks findings"
            L5_SECRET_FOUND=true
        fi
        rm -f "$LEAKS_LOG"
    else
        echo "   gitleaks not found — running grep-based lightweight scan (SKIPPED-degraded)..."
        step_skip "L5" "gitleaks not installed — degraded to grep scan (brew install gitleaks)"
        report "- **Degraded:** gitleaks not found, using grep fallback"

        # Grep-based fallback: scan working tree (zero external tool dependency)
        GREP_HITS=""
        SOURCES_DIRS="${REPO_ROOT}/VowriteKit/Sources ${REPO_ROOT}/VowriteMac/Sources ${REPO_ROOT}/VowriteIOS/Sources ${REPO_ROOT}/VowriteKeyboard/Sources"

        # Check for OpenAI-style keys (but not in regex/doc files)
        if grep -rE 'sk-[A-Za-z0-9]{20,}' $SOURCES_DIRS --include="*.swift" 2>/dev/null \
            | grep -v 'placeholder\|example\|Placeholder\|YOUR_KEY\|<key>' | grep -q .; then
            GREP_HITS="${GREP_HITS}\n  - Possible OpenAI/Kimi key (sk-...) in source files"
        fi

        if grep -rE 'gsk_[A-Za-z0-9]{30,}' $SOURCES_DIRS --include="*.swift" 2>/dev/null | grep -q .; then
            GREP_HITS="${GREP_HITS}\n  - Possible Groq key (gsk_...) in source files"
        fi

        if grep -rE 'sk-ant-[A-Za-z0-9\-]{30,}' $SOURCES_DIRS --include="*.swift" 2>/dev/null | grep -q .; then
            GREP_HITS="${GREP_HITS}\n  - Possible Anthropic key in source files"
        fi

        if grep -rE 'GOCSPX-[A-Za-z0-9_\-]{20,}' $SOURCES_DIRS --include="*.swift" 2>/dev/null | grep -q .; then
            GREP_HITS="${GREP_HITS}\n  - Possible Google OAuth secret in source files"
        fi

        if [[ -n "$GREP_HITS" ]]; then
            step_fail "L5" "grep fallback detected potential secrets in source files" "P0"
            echo -e "  Hits:$GREP_HITS"
            report "- **Result:** FAIL (P0) via grep fallback"
            L5_SECRET_FOUND=true
        else
            step_pass "L5" "grep fallback: no obvious secrets in source files (SKIPPED-degraded)"
            report "- **Result:** PASS via grep fallback (degraded — install gitleaks for full coverage)"
        fi
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# L6 — iOS-macOS Feature Parity
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L6"; then
    echo ""
    hr
    echo "▶ L6 — iOS-macOS Feature Parity"
    report ""
    report "## L6 — iOS-macOS Feature Parity"

    PARITY_SCRIPT="${REPO_ROOT}/scripts/check-parity.sh"
    if [[ -x "$PARITY_SCRIPT" ]]; then
        if bash "$PARITY_SCRIPT" 2>&1; then
            step_pass "L6" "No parity gaps detected"
            report "- **Result:** PASS"
        else
            step_fail "L6" "Parity gaps found — iOS may be missing features implemented on Mac" "P2"
            report "- **Result:** FAIL (P2) — parity gaps detected"
        fi
    else
        step_skip "L6" "scripts/check-parity.sh not found or not executable"
        report "- **Result:** SKIPPED — check-parity.sh missing"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# L7 — test.sh Security + Bundle Checks
# Reuses ops/scripts/test.sh output (security and bundle validation sections).
# We run the full test.sh and capture its security/bundle portions.
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L7"; then
    echo ""
    hr
    echo "▶ L7 — Security + Bundle (via ops/scripts/test.sh)"
    report ""
    report "## L7 — Security + Bundle Checks"

    TEST_SCRIPT="${REPO_ROOT}/ops/scripts/test.sh"
    if [[ -x "$TEST_SCRIPT" ]]; then
        TEST_LOG="$(mktemp /tmp/vowrite-testsuite-XXXXXX.log)"
        # Run test.sh (may fail overall — we capture output and check security/bundle sections)
        cd "${REPO_ROOT}" && bash "$TEST_SCRIPT" 2>&1 | tee "$TEST_LOG" || true

        SECURITY_FAILS=$(grep -c "❌.*[Ss]ecurity\|❌.*API key\|❌.*hardcoded" "$TEST_LOG" || true)
        BUNDLE_FAILS=$(grep -c "❌.*Bundle\|❌.*Info.plist\|❌.*Entitlements" "$TEST_LOG" || true)

        if [ "$SECURITY_FAILS" -gt 0 ]; then
            step_fail "L7" "test.sh: $SECURITY_FAILS security check failure(s)" "P1"
            report "- **Security:** FAIL (P1) — $SECURITY_FAILS failures"
        else
            step_pass "L7" "test.sh: security checks passed"
            report "- **Security:** PASS"
        fi

        if [ "$BUNDLE_FAILS" -gt 0 ]; then
            step_fail "L7" "test.sh: $BUNDLE_FAILS bundle check failure(s)" "P2"
            report "- **Bundle:** FAIL (P2) — $BUNDLE_FAILS failures"
        else
            step_pass "L7" "test.sh: bundle checks passed"
            report "- **Bundle:** PASS"
        fi
        rm -f "$TEST_LOG"
    else
        step_skip "L7" "ops/scripts/test.sh not found or not executable"
        report "- **Result:** SKIPPED"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# L8 — Custom grep security scan (zero external tool dependency)
# Scans for: transcript/key data in logs, App Group plaintext, hasFullAccess leaks
# This step ALWAYS runs regardless of tool availability.
# ─────────────────────────────────────────────────────────────────────────────
if should_run "L8"; then
    echo ""
    hr
    echo "▶ L8 — Custom Security Grep Scan (zero external tool dependency)"
    report ""
    report "## L8 — Custom Security Grep Scan"

    SOURCES_DIRS=(
        "${REPO_ROOT}/VowriteKit/Sources"
        "${REPO_ROOT}/VowriteMac/Sources"
        "${REPO_ROOT}/VowriteIOS/Sources"
        "${REPO_ROOT}/VowriteKeyboard/Sources"
    )

    L8_FAILS=0
    L8_WARNINGS=0

    # ── L8.1 Transcript/key data adjacent to log calls ──
    echo "  Checking for transcript/key data in logging calls..."
    LOG_PATTERN='(print|NSLog|os_log|Logger)[^)]*\([^)]*(transcript|polished|rawText|finalText|rawTranscript|apiKey|token|secret)'
    LOG_HITS=""
    for dir in "${SOURCES_DIRS[@]}"; do
        if [[ -d "$dir" ]]; then
            HITS=$(grep -rEn "$LOG_PATTERN" "$dir" --include="*.swift" 2>/dev/null || true)
            if [[ -n "$HITS" ]]; then
                LOG_HITS+="$HITS"$'\n'
            fi
        fi
    done

    if [[ -n "$LOG_HITS" ]]; then
        step_fail "L8" "Possible user-content leak in log calls (transcript/key data)" "P1"
        echo "$LOG_HITS" | head -10
        report "- **L8.1 Transcript leak in logs:** FAIL (P1)"
        report '  ```'
        report "$(echo "$LOG_HITS" | head -5)"
        report '  ```'
        L8_FAILS=$((L8_FAILS + 1))
    else
        step_pass "L8" "L8.1: no transcript/key data adjacent to log calls"
        report "- **L8.1 Transcript leak in logs:** PASS"
    fi

    # ── L8.2 App Group UserDefaults plaintext transcript storage ──
    echo "  Checking for App Group UserDefaults storing transcript data..."
    AG_PATTERN='UserDefaults\(suiteName.*\)\s*\?\??\s*\.set\s*\(.*[Tt]ranscript|set\([^,]*(transcript|rawText|polishedText|finalText)'
    AG_HITS=""
    for dir in "${SOURCES_DIRS[@]}"; do
        if [[ -d "$dir" ]]; then
            HITS=$(grep -rEn "$AG_PATTERN" "$dir" --include="*.swift" 2>/dev/null || true)
            if [[ -n "$HITS" ]]; then
                AG_HITS+="$HITS"$'\n'
            fi
        fi
    done

    if [[ -n "$AG_HITS" ]]; then
        step_fail "L8" "App Group UserDefaults storing plaintext transcript data" "P1"
        echo "$AG_HITS" | head -5
        report "- **L8.2 App Group plaintext transcript:** FAIL (P1)"
        L8_FAILS=$((L8_FAILS + 1))
    else
        step_pass "L8" "L8.2: no App Group UserDefaults plaintext transcript writes"
        report "- **L8.2 App Group plaintext transcript:** PASS"
    fi

    # ── L8.3 hasFullAccess ungated network calls in Keyboard extension ──
    echo "  Checking for ungated network calls in Keyboard extension..."
    KBD_DIR="${REPO_ROOT}/VowriteKeyboard/Sources"
    if [[ -d "$KBD_DIR" ]]; then
        # Find URLSession/network calls NOT preceded by hasFullAccess check in same file
        NETWORK_FILES=$(grep -rl 'URLSession\|URLRequest\|dataTask\|httpTask' "$KBD_DIR" --include="*.swift" 2>/dev/null || true)
        UNGATED_FILES=""
        for f in $NETWORK_FILES; do
            if ! grep -q 'hasFullAccess\|textDocumentProxy\|needsInputModeSwitchKey' "$f" 2>/dev/null; then
                UNGATED_FILES+="  $f\n"
            fi
        done

        if [[ -n "$UNGATED_FILES" ]]; then
            step_fail "L8" "Keyboard extension network calls without hasFullAccess guard" "P1"
            echo -e "$UNGATED_FILES" | head -5
            report "- **L8.3 hasFullAccess ungated network:** FAIL (P1)"
            L8_FAILS=$((L8_FAILS + 1))
        else
            step_pass "L8" "L8.3: no ungated network calls in Keyboard extension"
            report "- **L8.3 hasFullAccess ungated network:** PASS"
        fi
    else
        step_skip "L8" "L8.3: VowriteKeyboard/Sources not found"
        report "- **L8.3 hasFullAccess ungated network:** SKIPPED"
    fi

    # ── L8 Summary ──
    if [[ "$L8_FAILS" -gt 0 ]]; then
        report ""
        report "**L8 overall: $L8_FAILS check(s) failed**"
    else
        report ""
        report "**L8 overall: all checks passed**"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# 汇总
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  Review Scan Summary"
echo "══════════════════════════════════════════════════════════════"
printf "  %-10s %-10s %-10s\n" "PASS" "FAIL" "SKIP"
printf "  %-10s %-10s %-10s\n" "$PASS_COUNT" "$FAIL_COUNT" "$SKIP_COUNT"
echo ""

for result in "${STEP_RESULTS[@]}"; do
    echo "  $result"
done

echo "══════════════════════════════════════════════════════════════"

report ""
report "## Summary"
report ""
report "| Status | Count |"
report "|--------|-------|"
report "| PASS   | $PASS_COUNT |"
report "| FAIL   | $FAIL_COUNT |"
report "| SKIP   | $SKIP_COUNT |"
report ""
report "### Step Results"
report ""
for result in "${STEP_RESULTS[@]}"; do
    report "- $result"
done
report ""
report "---"
report "*Generated by ops/scripts/review-scan.sh — review charter v1, 2026-05-15*"

# ─────────────────────────────────────────────────────────────────────────────
# 写报告文件
# ─────────────────────────────────────────────────────────────────────────────
if [[ -n "$REPORT_PATH" ]]; then
    printf '%s\n' "${REPORT_LINES[@]}" > "$REPORT_PATH"
    echo "  Report written to: $REPORT_PATH"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 退出码
# ─────────────────────────────────────────────────────────────────────────────
if $P0_P1_HIT; then
    echo ""
    echo "❌ P0/P1 findings detected — exit 1"
    exit 1
elif $P2_P3_HIT; then
    if $SOFT_MODE; then
        echo ""
        echo "⚠️  P2/P3 findings (--soft mode: exit 0)"
        exit 0
    else
        echo ""
        echo "⚠️  P2/P3 findings — exit 2"
        exit 2
    fi
else
    echo ""
    echo "✅ All checks passed — exit 0"
    exit 0
fi
